// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTL1gfU3H4P-0Af0_662bDea05nmNect8',
    appId: '1:889405317193:web:9d22a6024f527b36025f98',
    messagingSenderId: '889405317193',
    projectId: 'fasum-jovannathanieljie',
    authDomain: 'fasum-jovannathanieljie.firebaseapp.com',
    databaseURL: 'https://fasum-jovannathanieljie-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-jovannathanieljie.firebasestorage.app',
    measurementId: 'G-QCVL8FELLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzjuaWH5hGEgHD0dBVx9dk2htkgTnD0aQ',
    appId: '1:889405317193:android:ced41a5c5864a963025f98',
    messagingSenderId: '889405317193',
    projectId: 'fasum-jovannathanieljie',
    databaseURL: 'https://fasum-jovannathanieljie-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-jovannathanieljie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpggCLcS959mzMPPMI0vsi1syckHiQGIs',
    appId: '1:889405317193:ios:27d2378277a1a230025f98',
    messagingSenderId: '889405317193',
    projectId: 'fasum-jovannathanieljie',
    databaseURL: 'https://fasum-jovannathanieljie-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-jovannathanieljie.firebasestorage.app',
    iosBundleId: 'com.example.fasumJovannathanieljie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpggCLcS959mzMPPMI0vsi1syckHiQGIs',
    appId: '1:889405317193:ios:27d2378277a1a230025f98',
    messagingSenderId: '889405317193',
    projectId: 'fasum-jovannathanieljie',
    databaseURL: 'https://fasum-jovannathanieljie-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-jovannathanieljie.firebasestorage.app',
    iosBundleId: 'com.example.fasumJovannathanieljie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTL1gfU3H4P-0Af0_662bDea05nmNect8',
    appId: '1:889405317193:web:f77c88bc31c85d51025f98',
    messagingSenderId: '889405317193',
    projectId: 'fasum-jovannathanieljie',
    authDomain: 'fasum-jovannathanieljie.firebaseapp.com',
    databaseURL: 'https://fasum-jovannathanieljie-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-jovannathanieljie.firebasestorage.app',
    measurementId: 'G-EF06ERNK4T',
  );

}